import { StyleSheet } from 'react-native';

export const palette = {
    ink: `#253f68`,
    navy: `#253f68`,
    gold: `#f5bd4f`,
    goldDark: `#b67714`,
    background: `#ffffff`,
    onNavyTick: `rgba(255,255,255,0.4)`,
    onNavyMuted: `rgba(255,255,255,0.7)`,
    onNavyBorder: `rgba(255,255,255,0.28)`,
    muted: `rgba(37,63,104,0.64)`,
    border: `rgba(37,63,104,0.12)`,
    surface: `rgba(37,63,104,0.05)`,
    surfaceSoft: `rgba(37,63,104,0.025)`,
    surfaceWarm: `rgba(245,189,79,0.16)`,
};

export const styles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: palette.background,
    },
    page: {
        width: `100%`,
        maxWidth: 1060,
        alignSelf: `center`,
        paddingHorizontal: 24,
    },
    headerContainer: {
        width: `100%`,
        maxWidth: 1060,
        alignSelf: `center`,
        paddingHorizontal: 24,
    },
    header: {
        gap: 14,
        minHeight: 82,
        overflow: `hidden`,
        marginHorizontal: -24,
        paddingHorizontal: 24,
        flexDirection: `row`,
        alignItems: `center`,
        justifyContent: `space-between`,
        borderBottomWidth: 1,
        backgroundColor: palette.navy,
        borderBottomColor: palette.onNavyBorder,
    },
    headerWatermark: {
        top: -44,
        right: 58,
        opacity: 0.025,
        position: `absolute`,
    },
    headerBookmark: {
        gap: 7,
        padding: 10,
        borderRadius: 12,
        flexDirection: `row`,
        alignItems: `center`,
        backgroundColor: `rgba(255,255,255,0.07)`,
    },
    headerBookmarkText: {
        fontSize: 13,
        fontWeight: `600`,
        color: palette.background,
    },
    hero: {
        gap: 18,
        paddingTop: 42,
        paddingBottom: 36,
        marginHorizontal: -24,
        paddingHorizontal: 24,
        alignItems: `flex-start`,
        backgroundColor: palette.background,
    },
    eyebrow: {
        gap: 7,
        flexDirection: `row`,
        alignItems: `center`,
    },
    eyebrowDot: {
        width: 7,
        height: 7,
        borderRadius: 4,
        backgroundColor: palette.gold,
    },
    eyebrowText: {
        fontSize: 11,
        fontWeight: `700`,
        letterSpacing: 1.8,
        color: palette.navy,
    },
    heroTitle: {
        fontSize: 47,
        lineHeight: 52,
        fontWeight: `800`,
        letterSpacing: -2.1,
        color: palette.navy,
    },
    heroTitleAccent: {
        color: palette.goldDark,
    },
    heroDescription: {
        fontSize: 16,
        maxWidth: 490,
        lineHeight: 26,
        color: palette.muted,
    },
    search: {
        gap: 12,
        width: `100%`,
        minHeight: 60,
        borderWidth: 1,
        borderRadius: 15,
        paddingHorizontal: 17,
        flexDirection: `row`,
        alignItems: `center`,
        borderColor: palette.border,
        backgroundColor: palette.background,
    },
    searchIcon: {
        fontSize: 25,
        color: palette.navy,
    },
    searchInput: {
        flex: 1,
        fontSize: 15,
        paddingVertical: 16,
        color: palette.ink,
    },
    clearSearch: {
        width: 28,
        height: 28,
        borderRadius: 14,
        alignItems: `center`,
        justifyContent: `center`,
        backgroundColor: palette.surfaceSoft,
    },
    clearSearchText: {
        fontSize: 19,
        color: palette.muted,
    },
    heroCaption: {
        fontSize: 12,
        lineHeight: 20,
        color: palette.muted,
    },
    featurePanel: {
        gap: 18,
        padding: 24,
        borderRadius: 23,
        marginBottom: 34,
        backgroundColor: palette.navy,
    },
    featurePanelTop: {
        gap: 18,
        flexDirection: `row`,
        alignItems: `center`,
    },
    featurePanelText: {
        flex: 1,
        fontSize: 21,
        lineHeight: 28,
        fontWeight: `600`,
        letterSpacing: -0.4,
        color: palette.background,
    },
    ruler: {
        height: 36,
        overflow: `hidden`,
        flexDirection: `row`,
        justifyContent: `space-between`,
        borderTopWidth: 1,
        borderTopColor: palette.onNavyBorder,
    },
    rulerTick: {
        width: 1,
        height: 11,
        backgroundColor: palette.onNavyTick,
    },
    rulerTickLong: {
        height: 24,
        backgroundColor: palette.gold,
    },
    featurePanelCaption: {
        fontSize: 10,
        fontWeight: `600`,
        letterSpacing: 1.5,
        color: palette.onNavyMuted,
    },
    sectionEyebrow: {
        fontSize: 10,
        marginBottom: 10,
        fontWeight: `700`,
        letterSpacing: 1.6,
        color: palette.muted,
    },
    categories: {
        gap: 8,
        flexWrap: `wrap`,
        marginBottom: 34,
        flexDirection: `row`,
    },
    categoryChip: {
        gap: 7,
        borderWidth: 1,
        borderRadius: 12,
        paddingVertical: 13,
        paddingHorizontal: 14,
        flexDirection: `row`,
        alignItems: `center`,
        borderColor: palette.border,
        backgroundColor: palette.surfaceWarm,
    },
    categoryChipActive: {
        borderColor: palette.navy,
        backgroundColor: palette.navy,
    },
    categoryIcon: {
        fontSize: 18,
        color: palette.navy,
    },
    categoryText: {
        fontSize: 12,
        fontWeight: `600`,
        color: palette.navy,
    },
    activeText: {
        color: palette.background,
    },
    directoryHeading: {
        gap: 8,
        marginBottom: 22,
    },
    directoryTitle: {
        fontSize: 29,
        lineHeight: 36,
        fontWeight: `700`,
        letterSpacing: -0.9,
        color: palette.navy,
    },
    directoryDescription: {
        fontSize: 14,
        lineHeight: 22,
        color: palette.muted,
    },
    platformScroll: {
        gap: 7,
        paddingBottom: 5,
    },
    platformChip: {
        gap: 6,
        borderRadius: 9,
        paddingVertical: 11,
        paddingHorizontal: 12,
        flexDirection: `row`,
        alignItems: `center`,
        backgroundColor: palette.surfaceSoft,
    },
    platformChipActive: {
        backgroundColor: palette.gold,
    },
    platformText: {
        fontSize: 12,
        fontWeight: `600`,
        color: palette.navy,
    },
    resultsBar: {
        gap: 12,
        marginTop: 15,
        marginBottom: 18,
        flexWrap: `wrap`,
        flexDirection: `row`,
        alignItems: `center`,
        justifyContent: `space-between`,
    },
    resultsCount: {
        fontSize: 12,
        color: palette.muted,
    },
    sortControl: {
        gap: 10,
        flexDirection: `row`,
        alignItems: `center`,
    },
    sortButton: {
        gap: 5,
        paddingVertical: 7,
        flexDirection: `row`,
        alignItems: `center`,
    },
    sortText: {
        fontSize: 11,
        color: palette.muted,
    },
    sortTextActive: {
        fontWeight: `700`,
        color: palette.navy,
    },
    toolGrid: {
        gap: 16,
        flexWrap: `wrap`,
        marginBottom: 34,
        flexDirection: `row`,
    },
    toolCard: {
        gap: 15,
        width: `100%`,
        padding: 22,
        borderWidth: 1,
        borderRadius: 18,
        borderColor: palette.border,
        backgroundColor: palette.background,
    },
    toolCardTop: {
        gap: 12,
        flexDirection: `row`,
        alignItems: `center`,
        justifyContent: `space-between`,
    },
    toolIcon: {
        width: 51,
        height: 51,
        borderRadius: 14,
        alignItems: `center`,
        justifyContent: `center`,
    },
    toolIconText: {
        fontSize: 27,
        fontWeight: `600`,
    },
    saveButton: {
        width: 39,
        height: 39,
        borderWidth: 1,
        borderRadius: 12,
        alignItems: `center`,
        justifyContent: `center`,
        borderColor: palette.border,
    },
    saveButtonActive: {
        borderColor: palette.gold,
        backgroundColor: palette.surfaceWarm,
    },
    saveButtonText: {
        fontSize: 24,
        color: palette.navy,
    },
    toolName: {
        fontSize: 19,
        fontWeight: `700`,
        letterSpacing: -0.35,
        color: palette.navy,
    },
    toolDescription: {
        fontSize: 14,
        lineHeight: 23,
        color: palette.muted,
    },
    toolCardBottom: {
        gap: 14,
        marginTop: 3,
        paddingTop: 15,
        borderTopWidth: 1,
        flexDirection: `row`,
        alignItems: `center`,
        justifyContent: `space-between`,
        borderTopColor: palette.border,
    },
    toolPlatform: {
        flex: 1,
        fontSize: 11,
        color: palette.muted,
    },
    openTool: {
        gap: 5,
        paddingVertical: 6,
        flexDirection: `row`,
        alignItems: `center`,
    },
    openToolText: {
        fontSize: 12,
        fontWeight: `700`,
        color: palette.navy,
    },
    emptyState: {
        gap: 13,
        padding: 34,
        borderWidth: 1,
        borderRadius: 18,
        alignItems: `center`,
        marginBottom: 34,
        borderColor: palette.border,
        backgroundColor: palette.surfaceSoft,
    },
    emptyIcon: {
        fontSize: 35,
        color: palette.gold,
    },
    emptyTitle: {
        fontSize: 20,
        fontWeight: `700`,
        color: palette.navy,
    },
    emptyDescription: {
        fontSize: 14,
        lineHeight: 23,
        textAlign: `center`,
        color: palette.muted,
    },
    resetButton: {
        gap: 7,
        marginTop: 6,
        borderRadius: 10,
        paddingVertical: 12,
        paddingHorizontal: 18,
        flexDirection: `row`,
        backgroundColor: palette.gold,
    },
    resetButtonText: {
        fontSize: 13,
        fontWeight: `700`,
        color: palette.navy,
    },
    closingNote: {
        gap: 10,
        padding: 26,
        borderRadius: 18,
        marginBottom: 30,
        backgroundColor: palette.surfaceWarm,
    },
    closingTitle: {
        fontSize: 22,
        lineHeight: 29,
        fontWeight: `700`,
        letterSpacing: -0.5,
        color: palette.navy,
    },
    closingDescription: {
        fontSize: 14,
        lineHeight: 24,
        color: palette.muted,
    },
    footer: {
        gap: 14,
        paddingTop: 20,
        paddingBottom: 32,
        overflow: `hidden`,
        marginHorizontal: -24,
        paddingHorizontal: 24,
        borderTopWidth: 1,
        borderTopColor: palette.onNavyBorder,
        backgroundColor: palette.navy,
    },
    footerWatermark: {
        top: -18,
        right: -28,
        opacity: 0.03,
        position: `absolute`,
    },
    footerText: {
        fontSize: 11,
        lineHeight: 19,
        color: palette.onNavyMuted,
    },
    pressed: {
        opacity: 0.7,
        transform: [{ scale: 0.98 }],
    },
});
